modLoader="javafml"
loaderVersion="[40,)"
license="GNU LGPLv3"

[[mods]]
    modId="tanukidecor"
    version="18.2.0.2"
    displayName="Tanuki Decor"
    authors="skyjay1"
    credits=""
    description='''Large furniture mod'''

[[dependencies.tanukidecor]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.tanukidecor]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,)"
    ordering="NONE"
    side="BOTH"